### ISSUE TITLE
Deploy to Maven central repository

### ISSUE THREAD

**Issue by viclovsky** [viclovsky/swagger-coverage#10]

**Comment by Deep27** [comment]
It'd be good to see this project in maven central.
But while it's not, I can't use it in my project by just adding:
    ```
<repositories>
        <repository>
            <id>viclovsky</id>
            <url>https://dl.bintray.com/viclovsky/maven/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.viclovsky.swagger.coverage</groupId>
            <artifactId>swagger-coverage-rest-assured</artifactId>
            <version>1.1.1</version>
        </dependency>
    </dependencies>
```
I'm getting maven error about dependency not found.
Could you please tell me what causes this problem?
Thankyou!

**Comment by viclovsky** [comment]
Hi, @Deep27 
I'll create task for adding swagger-coverage into Maven central repository, so it will be available as soon as possible. "Dependency not found" sounds strange, I bet there is misprint somewhere. Could you sent the exact text of error and your pom.xml?

**Comment by Deep27** [comment]
I copied and pasted <repositories> and <dependency> from readme, when I got "Dependency not found" error on my remote pc. I guess that I just don't have access to any of repositories there except Maven and local ones.
Also I've just tried it on my home pc and it works.

Thank you for your reply!

**Comment by scripnichenko** [comment]
I was successful, adding dependency only: 
 ```
        <dependency>
            <groupId>com.github.viclovsky.swagger.coverage</groupId>
            <artifactId>swagger-coverage-rest-assured</artifactId>
            <version>1.3.0</version>
        </dependency>
```

Looks like issue has been solved.

**Comment by TheXby** [comment]
Hello,
There is only 1.3.0 in maven central. And in bintray only 1.3.5 (not 1.3.7)

**Comment by viclovsky** [comment]
https://issues.sonatype.org/browse/OSSRH-55153
