### ISSUE TITLE
Paramteres in the enpoints are not able to covered

### ISSUE THREAD

**Issue by karishma191119** [viclovsky/swagger-coverage#106]
I'm submitting a ... 
  - [x] bug report
  - [ ] feature request

 What is the current behavior?
paramters in the url or the endpoints are not covering,it is showing null <null> is not empty

if the current behavior is a bug, please provide steps to reproduce, broken swagger specification and swagger-coverage-output:

What is the expected behavior?

What is the motivation / use case for changing the behavior?
Generate coverage report for parameters 

![parameter](https://user-images.githubusercontent.com/102681575/161488599-17f64508-536b-4d81-bd36-d606b9632e0f.png)

**Comment by viclovsky** [comment]
Hi, @karishma191119 
Sounds like you have specification with broken paths in $ref 
I’ll fix $ref in the nearest future. 
To overcame the issue you should make workaround: list all files with specification in the only one file.

**Comment by viclovsky** [comment]
Ok, got it. Sounds like you should add special option : https://github.com/viclovsky/swagger-coverage#specification-parser-configuration 
"parseOptions": {
  "resolve": true
}
It your $ref has right paths => all should work fine.
In nearest release, I’ll add switching on $refs by default.

**Comment by karishma191119** [comment]
> Ok, got it. Sounds like you should add special option : https://github.com/viclovsky/swagger-coverage#specification-parser-configuration
> 
> ```
> "parseOptions": {
>   "resolve": true
> }
> ```
> 
> It your $ref has right paths => all should work fine. In nearest release, I’ll add switching on $refs by default.

**Comment by karishma191119** [comment]
> Ok, got it. Sounds like you should add special option : https://github.com/viclovsky/swagger-coverage#specification-parser-configuration
> 
> ```
> "parseOptions": {
>   "resolve": true
> }
> ```
> 
> It your $ref has right paths => all should work fine. In nearest release, I’ll add switching on $refs by default.

Thank you for responding @viclovsky,
    I tried of this solution in many ways to implement,but it dosent work,Can you please allobrate how to pass this "parseOptions parameter"...It will help us if you provide detail solution and also hope that you will add this $ref in this tool
