### ISSUE TITLE
How to change the swagger-coverage-output folder location?

### ISSUE THREAD

**Issue by vadimglushonkov** [viclovsky/swagger-coverage#112]
Can't find a way to do it with the config, what if we want to put this output to another location?

**Comment by Goralive** [comment]
So to override this constants https://github.com/viclovsky/swagger-coverage/blob/master/swagger-coverage-commons/src/main/java/com/github/viclovsky/swagger/coverage/SwaggerCoverageConstants.java
you need to provide a new writer into the filter (FileSystemOutputWriter). The writer can be different.

`SwaggerCoverageV3RestAssured(FileSystemOutputWriter(Paths.get("build/bob")))` -> should create folder bob in build.

I hope it help's!
