### ISSUE TITLE
How to use this lib? 

### ISSUE THREAD

**Issue by SergeyPirogov** [viclovsky/swagger-coverage#14]
Hello, I would like to help with contribution to this project, but at first it’s not clear how to integrate and use it in the project

**Comment by viclovsky** [comment]
Hi @SergeyPirogov 
I have added README.md with explanation of how to use swagger-coverage. Don't hesitate to contact me if you have any questions.

**Comment by SergeyPirogov** [comment]
@viclovsky Thank you, will try it and provide a feedback
