### ISSUE TITLE
Missed requests

### ISSUE THREAD

**Issue by Zap4ick** [viclovsky/swagger-coverage#29]
Hi!
Somehow I have many my requests in "missed" tab, although I have these endpoints specified in swagger.json. These are: PATCH request (e.g. /registration/requests/9223372036854775800 PATCH) and POST endpoints where parameter is not the last string (e.g. /users/removal/19063/apply POST).
Should the app work fine with them?

**Comment by viclovsky** [comment]
Hi, @Zap4ick 
Unfortunately,  swagger-coverage does compare endpoints as strings, that is,  /registration/requests/9223372036854775800 PATCH != /registration/requests/{yourParam}. 

In case issue is urgent I don't mind if you implement more complicated comparing here and open PR. Thanks.

**Comment by Zap4ick** [comment]
hmm, but it is according to screenshoot in readme :)
ok, thanks!

**Comment by TemaMak** [comment]
@Zap4ick 
for correct compare you must call 
patch("/registration/requests/{yourParam}","9223372036854775800") instead
patch(" /registration/requests/9223372036854775800")

**Comment by TemaMak** [comment]
@Zap4ick 
you need to find the .json that is generated when this endpoint is called and compare field paths[] with the value that is written in the swagger.json

**Comment by Zap4ick** [comment]
well, i didn't realize the name of parameter should be the same :)

**Comment by viclovsky** [comment]
Fixed in 1.3.0.
