### ISSUE TITLE
support Springdoc OpenApi

### ISSUE THREAD

**Issue by dstoianov** [viclovsky/swagger-coverage#37]
The tool is great!
Thank you

how about this library https://github.com/springdoc/springdoc-openapi
do you have any plan to support this in the future?

**Comment by viclovsky** [comment]
Hi, @dstoianov 
Please, check [issue](https://github.com/viclovsky/swagger-coverage/issues/9)

**Comment by dstoianov** [comment]
duplicate hare https://github.com/viclovsky/swagger-coverage/issues/9
