### ISSUE TITLE
Wrong api handler in report

### ISSUE THREAD

**Issue by SergeyPirogov** [viclovsky/swagger-coverage#44]
The report shows the wrong handlers:

api.json data
[api-docs.zip](https://github.com/viclovsky/swagger-coverage/files/4415178/api-docs.zip)

There is no POST /episodes/{id} in son, but the report says that it exists

![image](https://user-images.githubusercontent.com/4622856/78138418-890f7d00-742f-11ea-8e26-ef027d03eb2b.png)

**Comment by viclovsky** [comment]
Hi, @SergeyPirogov. 
Handler `POST  /episodes/{id}` exists in api.json.
Please check specification again, for example, with swagger-editor:
![изображение](https://user-images.githubusercontent.com/20776437/78139493-4cdd1c00-7431-11ea-81a9-409cb324a11a.png)

**Comment by SergeyPirogov** [comment]
Hm, will check it. Is it possible to split your report the same way grouping by controllers?

**Comment by viclovsky** [comment]
Yes, it is. It will be in next release possibly.

**Comment by viclovsky** [comment]
Fixed in 1.3.0
