### ISSUE TITLE
Cant download swagger commandline

### ISSUE THREAD

**Issue by Snoopke** [viclovsky/swagger-coverage#54]
`wget https://dl.bintray.com/viclovsky/maven/com/github/viclovsky/swagger/coverage/swagger-coverage-commandline/{latest-swagger-coverage-version}/swagger-coverage-commandline-{latest-swagger-coverage-version}.zip
unzip swagger-coverage-commandline-{latest-swagger-coverage-version}.zip`

This returns 404

**Comment by TemaMak** [comment]
just replace {latest-swagger-coverage-version} with real value of version. For example:

`wget https://dl.bintray.com/viclovsky/maven/com/github/viclovsky/swagger/coverage/swagger-coverage-commandline/1.3.0/swagger-coverage-commandline-1.3.0.zip unzip swagger-coverage-commandline-1.3.0.zip`
