### ISSUE TITLE
How to generate swagger data from tests?

### ISSUE THREAD

**Issue by Snoopke** [viclovsky/swagger-coverage#55]
Thanks for your project! I tried your example from run.sh, it works perfect!

Now I'm trying to apply it to my project. I have swagger from developers  and my python tests.
I need to generate swagger from tests then to compare, but I don’t understand how to do it exactly.

Dont you know how can i do it in python? Sorry, if the question is dumb

**Comment by viclovsky** [comment]
Hi, @Snoopke 
Swagger-coverage supports listener for rest-assured from the box at the moment. If you use another test framework you need to add custom listener/filter/interceptor or proxy, which save information about calls in swagger format(for example https://github.com/viclovsky/swagger-coverage/blob/master/swagger-coverage-commandline/src/test/resources/swagger-coverage-output/one_parameter.json) in specific folder on executing tests.
