### ISSUE TITLE
Condition name - "path" always stays red

### ISSUE THREAD

**Issue by SergeyVinickiy** [viclovsky/swagger-coverage#67]
In report - "path" parameter stays red. But for all request we always send values in those parameters, they are never empty
Please see example in the picture 

![image](https://user-images.githubusercontent.com/37349791/100337619-4c0c8200-2fe0-11eb-9048-8b2883cfeed6.png)

**Comment by TemaMak** [comment]
@SergeyVinickiy 
Unchecked condition is marked in red. In this case, the report says that you do not check the case when appMarketappId is empty in your tests.

**Comment by SergeyVinickiy** [comment]
We are using HttpClients
 url generated outside "/api/object/1"

**Comment by TemaMak** [comment]
@SergeyVinickiy 
for correct path-variable checked you must write api call like
` ... "paths": {
    "/api/pbject/{id}": {
      "get": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "x-example": "1"
          }, ...`

If your output file does not have a section **parameters**, then the swagger-coverage will consider that the specified parameter is empty.

**Comment by SergeyVinickiy** [comment]
Yes, I see,
we don't save it this way. Thank you!
