### ISSUE TITLE
How to mark some endpoints as deprecated

### ISSUE THREAD

**Issue by TheXby** [viclovsky/swagger-coverage#70]
Hello,
We have controller which is deprecated but still work. I want to exclude it from report.
How can I do this?

**Comment by JamalZeynalov** [comment]
Hi, @TheXby 
I did this change locally. Waiting for the access to create a Pull Request.
@viclovsky, please let me know how to create it.

**Comment by JamalZeynalov** [comment]
# Before:
![before](https://user-images.githubusercontent.com/8066700/105961658-784b8a00-6087-11eb-9dd7-d74a6fc3af46.png)
# After:
![after](https://user-images.githubusercontent.com/8066700/105961652-7681c680-6087-11eb-8283-eb8b90168a66.png)

**Comment by JamalZeynalov** [comment]
Hi, @TheXby I just implemented this kind of change and created a pull request. Check it, maybe it is what you need.
https://github.com/viclovsky/swagger-coverage/pull/72
