### ISSUE TITLE
Support OAS3

### ISSUE THREAD

**Issue by viclovsky** [viclovsky/swagger-coverage#9]

**Comment by R2Rs** [comment]
When do you plan to implement OAS3 support?

**Comment by viclovsky** [comment]
Hi, @R2Rs 
Unfortunately, I don't have any plans to support it in nearest future, sorry. But if it is critical and urgent, I don't mind to review your PR request.

**Comment by Emilio-Pega** [comment]
Hi, so I gave the OAS 3 support a go: https://github.com/viclovsky/swagger-coverage/issues/9 if you have a chance to take a look
