### ISSUE TITLE
Version 1.4.3. does not resolve some of the dependencies correctly when using Gradle

### ISSUE THREAD

**Issue by Fresh-D101** [viclovsky/swagger-coverage#93]
[//]: # (
. This repository's issues are reserved for feature requests and bug reports.
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - Bad perfomance with a large specification
. - Support OAS3 
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request

#### What is the current behavior?
When using 'com.github.viclovsky:swagger-coverage-commandline:1.4.3' or 'com.github.viclovsky:swagger-coverage-commons:1.4.3' in gradle, following error message appears when trying to build the project:

> Could not resolve all files for configuration ':testRuntimeClasspath'.
   > Could not find io.swagger.parser.v3:swagger-parser:.
     Required by:
         project : > com.github.viclovsky:swagger-coverage-commandline:1.4.3
   > Could not find log4j:log4j:.
     Required by:
         project : > com.github.viclovsky:swagger-coverage-commandline:1.4.3
         project : > com.github.viclovsky:swagger-coverage-commons:1.4.3
   > Could not find com.beust:jcommander:.
     Required by:
         project : > com.github.viclovsky:swagger-coverage-commandline:1.4.3
   > Could not find org.springframework:spring-web:.
     Required by:
         project : > com.github.viclovsky:swagger-coverage-commandline:1.4.3
   > Could not find org.freemarker:freemarker:.
     Required by:
         project : > com.github.viclovsky:swagger-coverage-commons:1.4.3
   > Could not find io.swagger.core.v3:swagger-core:.
     Required by:
         project : > com.github.viclovsky:swagger-coverage-commons:1.4.3

Not sure if related to #92 or #91.
I also tried the same setup with 1.4.1 and everything worked just fine.

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context
)

**Comment by viclovsky** [comment]
I think, problem is here https://github.com/viclovsky/swagger-coverage/pull/86 (gradle/wrapper/gradle-wrapper.properties).  I have bumped gradle version 5.6.2 to 7.0.2 and caught backward compatibility problems with dependencies which I haven't expected.

**Comment by viclovsky** [comment]
Hi, @Fresh-D101 
I have tried to reproduce your problem. Here is an example project with swagger-coverage 1.4.3: https://github.com/viclovsky/swagger-coverage-example 

But I haven't caught the issue. Could you make PR (with reproduced issue) in my repo: https://github.com/viclovsky/swagger-coverage-example ?

**Comment by Fresh-D101** [comment]
Hi @viclovsky ,
thank you for your reply! I will try to make a PR later today, latest tomorrow!

**Comment by Fresh-D101** [comment]
Hi @viclovsky.
I made a PR which you can find here: https://github.com/viclovsky/swagger-coverage-example/pull/2

**Comment by DmytroFaliush** [comment]
the same issue
